# _config.yml
title: "Data Analysis Portfolio"
author: "Azubuike Emmanuel"

# Theme
theme: jekyll-theme-cayman

# Site settings
url: "https://azubuikeemmanuel.github.io"
baseurl: "/portfolio"

# Social media links
social_links:
  github: "https://github.com/azubuikeemmanuel"
  linkedin: "https://linkedin.com/in/azubuike-emmanuel01"
  



# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Plugins for extra functionality
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed


# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Azubuike Emmanuel"

