title: "My Data Analysis Portfolio"

logo: documents/IMG_1097.jpeg
theme: minima

# Include custom CSS for styling
plugins:
  - jekyll-seo-tag

# Add navigation links
header_pages:
  - index.md
  - projects.md
  - about.md

# Add custom CSS
sass: assets/css/style.scss
  style: compressed


